<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/header.phtml');?> 

  <body>  
	   <?php echo Yaf\View\Simple::render(VIEWPATH.'/public/login.phtml');?>  
 
        <?php echo Yaf\View\Simple::render(VIEWPATH . '/public/menu.phtml'); ?>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<div class="show-top-grids">
				<div class="col-sm-8 single-left">
					<div class="song">
						<div class="song-info">
							<h3><?php echo $detail['video_title']; ?></h3>	
					</div>
						 <div class="video-plays" style="width: 100%; height: 370px">
							<video id="demo-video" class="video-js vjs-big-play-centered "></video>
						 </div>
					</div> 

					<div class="clearfix"> </div>
					<div class="published"> 
							<div class="load_more">	
								<ul id="myList">
								   <li><div class="bshare-custom icon-medium"><a title="分享到" href="http://www.bShare.cn/" id="bshare-shareto" class="bshare-more">分享到</a><a title="分享到QQ空间" class="bshare-qzone"></a><a title="分享到新浪微博" class="bshare-sinaminiblog"></a><a title="分享到Facebook" class="bshare-facebook"></a><a title="分享到Twitter" class="bshare-twitter"></a><a title="分享到LinkedIn" class="bshare-linkedin"></a><a title="分享到微信" class="bshare-weixin"></a><a title="分享到腾讯微博" class="bshare-qqmb"></a><a title="分享到网易微博" class="bshare-neteasemb"></a><a title="更多平台" class="bshare-more bshare-more-icon more-style-addthis"></a><span class="BSHARE_COUNT bshare-share-count">0</span></div><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=3&amp;lang=zh"></script><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
                                   </li> 
								</ul>
							</div>
					</div>

					<div class="all-comments">
						<div class="all-comments-info">
							<a href="javascript:;" >Comments( <span class="commentAll">0</span> )</a>
							<div class="box"> 
							        <input type="hidden"  value="<?php echo $type ?>" class="hidtype"/>
							        <input type="hidden"  value="<?php echo $id ?>"   class="hidid"/>
							        <input type="hidden" value="<?php echo $formKey; ?>" class="formKey">
									<textarea placeholder="Message" class="Message" required=" "></textarea>
									<input type="submit" class="submit" value="SEND">
									<div class="clearfix"> </div> 
							</div> 
						</div>
						<div class="media-grids">
							<div class="media">
								<h5>zxr</h5> 
								<div class="media-body">
									<p>哎呦，不错哟！</p>
									<span style="display:none" >View all posts by :<a href="#"> Admin </a></span>
								</div>
							</div>

						</div>
					</div>
				</div>
				<div class="col-md-4 single-right">
					<h3>Up Next</h3>
					<div class="single-grid-right">
					   <?php foreach ($detail['recommend'] as $key => $value) { 
                             if($id ==  $value['id']){
                             	continue;
                             }
					   	?> 
						  <div class="single-right-grids">
							<div class="col-md-4 single-right-grid-left">
								<a href="<?php echo $value['link']; ?>"><img src="<?php echo $value['img_url']; ?>" alt="<?php echo $value['video_title']; ?>" /></a>
							</div>
							<div class="col-md-8 single-right-grid-right">
								<a href="<?php echo $value['link']; ?>" class="title"> <?php echo $value['video_title']; ?></a>
								<p class="author"><a href="<?php echo $value['link']; ?>" class="author"><?php echo $value['author']; ?></a></p>
								<p class="views"><?php echo $value['playback_times']; ?> views</p>
							</div>
							<div class="clearfix"> </div>
						  </div> 
					   <?php  } ?>
						 
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<!-- footer -->
			 <?php echo Yaf\View\Simple::render(VIEWPATH . '/public/footer.phtml');?> 
			<!-- //footer -->
		</div>
		<div class="clearfix"> </div>
	<div class="drop-menu">
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
		  <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
		</ul>
	</div>  
    <script>
		 $(document).ready(function () {
			 size_li = $("#myList li").size();
				 x=1;
			    $('#myList li:lt('+x+')').show();
				 $('#loadMore').click(function () {
					  x= (x+1 <= size_li) ? x+1 : size_li;
						$('#myList li:lt('+x+')').show();
						});
					$('#showLess').click(function () {
					   x=(x-1<0) ? 1 : x-1;
				  $('#myList li').not(':lt('+x+')').hide();
		    });
		 });
	 </script> 
	 <!--播放器-->
	 <link href="https://player.qiniucc.com/sdk/latest/qiniuplayer.min.css" rel="stylesheet">
     <script src="https://player.qiniucc.com/sdk/latest/qiniuplayer.min.js"></script>
     <script type="text/javascript">
	 var options = {
	 	poster:"<?php echo $detail['img_url']; ?>", 
	    controls: true,
	    url: "<?php echo $detail['video_url']; ?>",
	    //url: 'http://og9dz2jqu.cvoda.com/Zmlyc3R2b2RiOm9jZWFucy0xLm1wNA==_q00000001.m3u8',
	    type: 'mp4',
	    preload: true,
	    autoplay: false // 如为 true，则视频将会自动播放
	};
	var player = new QiniuPlayer('demo-video', options); 
	
    /* 
     提交评论
     zxr 
    */
   var send = 0;
   var user = '<?php echo json_encode($user); ?>';
	$(".submit").click(function(event) {
		if(send == 1){
			alert('正在提交中,请稍后....');
			return false;
		}
		var Message = $(".Message").val();
		var hidtype = $(".hidtype").val();
		var hidid   = $(".hidid").val();
		var formKey = $(".formKey").val();
		if(Message == '' ||  Message.length < 5){
			alert('请输入评论内容');
			return false;
		}
		if(hidtype == '' || hidid == '' || formKey == ''){
           alert("非法操作");
           return false; 
		}
		if(user == '' || user.length < 3){
           alert("请登录");
           return false; 
		} 
      var params = {
          'formKey':formKey,
          'id' : hidid,
          'type' : hidtype,
          'content' : Message
        };
      $.ajax({
     	url: '/comment/published',
     	type: 'POST',
     	dataType: 'json',
     	data: params,
     	beforeSend:function(){
     		send = 1;
     	}
     })
     .done(function(data) {
     	alert(data.msg); 
     	send = 0;
     })
     .fail(function(data) { 
     	alert("提交失败");
     	send = 0;
     })
     .always(function(data) { 
     	send = 0;
     }); 
 }); 

//获取评论列表
 $(document).ready(function() {
 	 getcommitList();
 });

</script>

  </body>
</html>