<?php
$optionsRender = function($key) use ($options) {
    if (isset($options[$key])) {
        return $options[$key];
    } else {
        return '';
    }
};
?> 
 <!-- footer -->
            <div class="footer">
                <div class="footer-grids">
                    <div class="footer-top">
                        <div class="footer-top-nav">
                            <ul>
                                <li><a href="/transitpage/about">About</a></li>
                                <li><a href="/transitpage/press">Press</a></li>
                                <li><a href="/transitpage/copyright">Copyright</a></li>
                                <li><a href="/transitpage/creators">Creators</a></li>
                                <li><a href="#">Advertise</a></li>
                                <li><a href="/transitpage/developers">Developers</a></li>
                            </ul>
                        </div>
                        <div class="footer-bottom-nav">
                            <ul>
                                <li><a href="/transitpage/terms">Terms</a></li>
                                <li><a href="/transitpage/privacy">Privacy</a></li>
                                <li><a href="#small-dialog4" class="play-icon popup-with-zoom-anim">Send feedback</a></li>
                                <li><a href="/transitpage/privacy">Policy & Safety </a></li>
                                <li><a href="/transitpage/try">Try something new!</a></li>
                            </ul>
                        </div>
                    </div> 
                </div>
            </div>
            <!-- //footer -->


<?php echo  Base\Tools::script($optionsRender('script'));?>
        <script>
                                            $(document).ready(function() {
                                            $('.popup-with-zoom-anim').magnificPopup({
                                                type: 'inline',
                                                fixedContentPos: false,
                                                fixedBgPos: true,
                                                overflowY: 'auto',
                                                closeBtnInside: true,
                                                preloader: false,
                                                midClick: true,
                                                removalDelay: 300,
                                                mainClass: 'my-mfp-zoom-in'
                                            });
                                                                                                            
                                            });

                            // You can also use "$(window).load(function() {"
                            $(function () {
                              // Slideshow 4
                              $("#slider3").responsiveSlides({
                                auto: true,
                                pager: false,
                                nav: true,
                                speed: 500,
                                namespace: "callbacks",
                                before: function () {
                                  $('.events').append("<li>before event fired.</li>");
                                },
                                after: function () {
                                  $('.events').append("<li>after event fired.</li>");
                                }
                              });
                        
                            });


                            $( "li a.menu1" ).click(function() {
                            $( "ul.cl-effect-2" ).slideToggle( 300, function() {
                            // Animation complete.
                            });
                            });


                            $( "li a.menu" ).click(function() {
                            $( "ul.cl-effect-1" ).slideToggle( 300, function() {
                            // Animation complete.
                            });
                            });


                            $( ".top-navigation" ).click(function() {
                            $( ".drop-navigation" ).slideToggle( 300, function() {
                            // Animation complete.
                            });
                            });
                      
                           
  </script>