    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><h1><img src="<?php echo $logo; ?>" alt="" /></h1></a>
        </div>

  <div id="navbar" class="navbar-collapse collapse">
			<div class="top-search">
				<form class="navbar-form navbar-right" action="/search/" method="GET">
					<input type="text" name="keyword" class="form-control" placeholder="Search...">
					<input type="submit" value=" ">
				</form>
			</div>   
<div class="header-top-right"> 
	 <div class="signin">
	 <?php if(!empty($user)){ ?>
	    <a href="javascript:;" class="play-icon popup-with-zoom-anim"><?php echo $user['nickname']; ?></a>  
	 <?php }else{ ?> 
		 <a href="#small-dialog2" class="play-icon popup-with-zoom-anim sigin_up_button">Sign Up</a>  
		 <?php } ?>

			 <div id="small-dialog2" class="mfp-hide">
				  <h3>Create Account</h3> 
					  <div class="social-sits"> 
						  <div class="button-bottom">
							  <p>Already have an account? <a href="#small-dialog" class="play-icon popup-with-zoom-anim">Login</a></p>
						  </div>
					 </div>
				 <div class="signup">
			 
				 <input type="text" class="email e-mail" placeholder="Email" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?" title="Enter a valid email"/>
												
				 <input type="text" class="email phone" placeholder="Mobile Number" maxlength="11" pattern="[1-9]{1}\d{10}" title="Enter a valid mobile number" />

				 <input type="password" class="pwd" placeholder="Password" required="required" pattern=".{6,}" title="Minimum 6 characters required" autocomplete="off" /> 

				 <input type="text" class="email nickname" placeholder="nickname"   title="Please enter your nickname" autocomplete="off" /> 


				 <input type="hidden"  value="" class="login_formKey" />

				 <input type="submit" class="subsignup"  value="Sign Up"/>
				  
			 </div>
			 <div class="clearfix"> </div>
			     </div>	 
			 </div>
				<div class="signin">
                <?php if(!empty($user)){ ?>
					<a href="javascript:;" class="play-icon logout_button">Sign out</a>
		        <?php }else{ ?>
                    <a href="#small-dialog" class="play-icon popup-with-zoom-anim sigin_in_button ">Sign In</a>
		        <?php } ?>

					<div id="small-dialog" class="mfp-hide">
						<h3>Login</h3>
						<div class="social-sits"> 
							<div class="button-bottom">
								<p>New account? <a href="#small-dialog2" class="play-icon popup-with-zoom-anim">Signup</a></p>
							</div>
						</div>
						<div class="signup"> 
								<input type="text" class="email username" placeholder="Enter email / mobile" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?"/>

								<input type="password" class="passwd"  placeholder="Password" required="required" pattern=".{6,}" title="Minimum 6 characters required" autocomplete="off" />

								<input type="hidden"  value="" class="login_formKey" />


								<input type="submit" class="signin_login"  value="LOGIN"/> 
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
  </div>

  <div class="clearfix"> </div>
      </div>
    </nav> 