<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/header.phtml');?> 

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><h1><img src="http://static.13520v.com/images/logo.png" alt="" /></h1></a>
        </div>

    <?php echo Yaf\View\Simple::render(VIEWPATH.'/public/login.phtml');?>  

		<div class="clearfix"> </div>
      </div>
    </nav>
	
        <?php echo Yaf\View\Simple::render(VIEWPATH . '/public/menu.phtml'); ?>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<div class="main-grids">
				<div class="top-grids">
					<div class="recommended-info">
						<h3>Current fashion</h3>
					</div>
					<?php foreach ($data['popular'] as $key => $value) { ?>  
					<div class="col-md-4 resent-grid recommended-grid slider-top-grids">
						<div class="resent-grid-img recommended-grid-img">
							<a href="<?php echo $value['link'] ?>"><img src="<?php echo $value['img_url'] ?>" alt="<?php echo $value['video_title'] ?>" /></a>
							<div class="time">
								<p><?php echo $value['play_duration'] ?></p>
							</div>
							<div class="clck">
								<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
							</div>
						</div>
						<div class="resent-grid-info recommended-grid-info">
							<h3><a href="<?php echo $value['link'] ?>" title="<?php echo $value['video_title'] ?>" class="title title-info"><?php echo $value['video_title'] ?></a></h3>
							<ul>
								<li><p class="author author-info"><a href="#" class="author"><?php echo $value['author'] ?> </a></p></li>
								<li class="right-list"><p class="views views-info"><?php echo $value['video_time_content'] ?></p></li>
							</ul>
						</div>
					</div> 
					 <?php } ?>

					<div class="clearfix"> </div>
				</div>
				
				<div class="recommended">
					<div class="recommended-grids">
						<div class="recommended-info">
							<h3>Funny</h3>
						</div> 
					
						<div  id="top" class="callbacks_container">
							<ul class="rslides" id="slider3"> 
							 	<li>
									<div class="animated-grids">
                                     <?php foreach ($data['funny'] as $key => $value) { ?> 
										<div class="col-md-3 resent-grid recommended-grid slider-first">
											<div class="resent-grid-img recommended-grid-img">
												<a href="<?php echo $value['link']; ?>"><img src="<?php echo $value['img_url']; ?>" alt="<?php echo $value['video_title']; ?>" /></a>
												<div class="time small-time slider-time">
													 
												</div>
												<div class="clck small-clck">
													<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
												</div>
											</div>
											<div class="resent-grid-info recommended-grid-info">
												<h5><a href="<?php echo $value['link']; ?>" title="<?php echo $value['video_title']; ?>" class="title"><?php echo $value['video_title']; ?></a></h5>
												<div class="slid-bottom-grids">
													<div class="slid-bottom-grid">
														<p class="author author-info"><a href="<?php echo $value['link']; ?>" class="author"><?php echo $value['author']; ?></a></p>
													</div>
													<div class="slid-bottom-grid slid-bottom-right">
														<p class="views views-info"><?php echo $value['play_count'] ?></p>
													</div>
													<div class="clearfix"> </div>
												</div>
											</div>
										</div>
										<?php } ?>

										<div class="clearfix"> </div>
									</div>
								</li> 
							</ul>
						</div>
					</div>
				</div>
				<div class="recommended">
                    <?php foreach ($data['music'] as $key => $value) { ?> 
					<div class="recommended-grids">
                          <?php if($key == 0){ ?>
						<div class="recommended-info">
							<h3>Music</h3>
						</div>
                          <?php } ?>
                         <?php foreach ($value as $k => $v) { ?> 
						<div class="col-md-3 resent-grid recommended-grid">
							<div class="resent-grid-img recommended-grid-img">
								<a href="<?php echo $v['link']; ?>"><img src="<?php echo $v['img_url']; ?>" alt="<?php echo $v['video_title']; ?>" /></a>
								<div class="time small-time">
									<p><?php echo $v['play_time']; ?></p>
								</div>
								<div class="clck small-clck">
									<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
								</div>
							</div>
							<div class="resent-grid-info recommended-grid-info video-info-grid">
								<h5><a href="<?php echo $v['link']; ?>" title="<?php echo $v['video_title'];?>" class="title"> <?php echo $v['video_title'];?></a></h5>
								<ul>
									<li><p class="author author-info"><a href="#" class="author"><?php echo $v['author'];?></a></p></li>
									<li class="right-list"><p class="views views-info"><?php echo $v['video_time_content'];?></p></li>
								</ul>
							</div>
						</div>
						 <?php  } ?>  
						<div class="clearfix"> </div>
					</div>
					<?php } ?> 
				</div>


				<div class="recommended">
				<?php foreach ($data['sports'] as $key => $value) { ?> 
					<div class="recommended-grids">
                        <?php if($key == 0){ ?>
						<div class="recommended-info">
							<h3>Sports</h3>
						</div>
						<?php } ?>
                       <?php foreach ($value as $k => $v) { ?> 
						<div class="col-md-3 resent-grid recommended-grid">
							<div class="resent-grid-img recommended-grid-img">
								<a href="<?php echo $v['link'] ?>"><img src="<?php echo $v['img_url'] ?>" alt="<?php echo $v['video_title'] ?>" /></a>
								<div class="time small-time">
									<p><?php echo $v['play_time'] ?></p>
								</div>
								<div class="clck small-clck">
									<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
								</div>
							</div>
							<div class="resent-grid-info recommended-grid-info video-info-grid">
								<h5><a href="<?php echo $v['link'] ?>" title="<?php echo $v['video_title'] ?>" class="title"><?php echo $v['video_title'] ?></a></h5>
								<ul>
									<li><p class="author author-info"><a href="#" class="author"><?php echo $v['author'] ?></a></p></li>
									<li class="right-list"><p class="views views-info"> <?php echo $v['video_time_content'] ?></p></li>
								</ul>
							</div>
						</div>
					 <?php } ?> 
						<div class="clearfix"> </div>
					</div>
             <?php } ?> 
				</div>
			</div>
			
			<!-- footer --> 
            <?php echo Yaf\View\Simple::render(VIEWPATH . '/public/footer.phtml');?> 
			<!-- //footer -->

		</div>
		<div class="clearfix"> </div>
	<div class="drop-menu">
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
		  <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
		</ul>
	</div>
   
  </body>
</html>