<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/header.phtml');?> 
  <body>
<?php echo Yaf\View\Simple::render(VIEWPATH.'/public/login.phtml');?>   
		<div class="developers">
			<div class="developers-banner">
				<!-- container -->
				<div class="container">
					<div class="developers-info">
						<h3>About me</h3>
						<p>人生难得几回搏，此时不搏待何时</p>
					</div>
				</div>
				<!-- //container -->
			</div>
			<div class="developers-grids">
				<!-- container -->
				<div class="container">
					<div class="developers-grid">
						<a href="single.html">Contact me</a>
						<p>Mailbox:strive965432@gmail.com</p>
						<p>Github:https://github.com/zhangxuanru</p> 
					</div> 
				</div>
				<!-- //container -->
			</div>
		</div>
			<!-- footer -->
			<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/footer.phtml');?> 
			<!-- //footer -->
		<div class="clearfix"> </div>
	<div class="drop-menu">
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
		  <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
		</ul>
	</div> 
  </body>
</html>