<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/header.phtml');?> 
  <body>
<?php echo Yaf\View\Simple::render(VIEWPATH.'/public/login.phtml');?>   
		<div class="developers">
			<div class="developers-banner">
				<!-- container -->
				<div class="container">
					<div class="developers-info">
						<h3>For Developers</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc blandit vulputate eleifend. Cras dignissim et massa eu varius. Etiam iaculis tellus id nunc gravida, id fermentum libero porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras commodo commodo luctus.</p>
					</div>
				</div>
				<!-- //container -->
			</div>
			<div class="developers-grids">
				<!-- container -->
				<div class="container">
					<div class="developers-grid">
						<a href="#">Demos</a>
						<p>Nunc vitae rutrum enim. Mauris at volutpat leo. Vivamus dapibus mi ut elit fermentum tincidunt. Vestibulum lobortis mauris maximus magna consectetur, non commodo velit vestibulum. Phasellus rutrum odio eu metus dignissim, nec feugiat nisi tempus. Nunc non nibh sagittis, rhoncus neque tempus, efficitur dolor. Suspendisse ornare sapien vitae mauris pharetra, sed eleifend ante luctus. Fusce mollis tortor sit amet ipsum suscipit semper.</p>
					</div>
					<div class="developers-grid">
						<a href="#">API Resources</a>
						<p>Pellentesque ultricies faucibus mauris, nec aliquam nunc ornare nec. Fusce mattis ultrices venenatis. Nam iaculis dignissim tellus, quis blandit sapien. Morbi eu arcu porttitor, bibendum augue sit amet, malesuada ex. Vivamus convallis molestie auctor. Donec viverra magna tortor.</p>
					</div>
					<div class="developers-grid">
						<a href="#">Showcase</a>
						<p>Integer sapien enim, suscipit ac convallis et, feugiat ac est. Suspendisse felis quam, iaculis eget metus vel, semper tempus quam. Integer eu mauris ante. Nulla fringilla lectus ac metus sodales suscipit. Cras non purus tincidunt, semper elit vel, porttitor turpis. Sed imperdiet, ex quis consequat congue, justo urna aliquam diam, a pretium nulla arcu sed nisi. Nam mi turpis, imperdiet ornare sodales vitae, cursus eu sem.</p>
					</div>
					<div class="developers-grid">
						<a href="#">Developer Stories</a>
						<p>Mauris vehicula rutrum velit, a scelerisque eros volutpat quis. Curabitur vel molestie leo, et sodales diam. Donec sem nibh, mattis non cursus nec, elementum ac lacus. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean vitae ipsum fermentum, commodo lectus et, euismod justo. Praesent congue lorem a quam porttitor, a laoreet felis fringilla.</p>
					</div>
				</div>
				<!-- //container -->
			</div>
		</div>
			<!-- footer -->
			<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/footer.phtml');?> 
			<!-- //footer -->
		<div class="clearfix"> </div>
	<div class="drop-menu">
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
		  <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
		</ul>
	</div> 
  </body>
</html>