<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/header.phtml');?> 
  <body> 
   <?php echo Yaf\View\Simple::render(VIEWPATH.'/public/login.phtml');?>   
    <?php echo Yaf\View\Simple::render(VIEWPATH . '/public/menu.phtml'); ?>  
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<div class="show-top-grids">
				<div class="main-grids news-main-grids">
					<div class="recommended-info">
						<h3>Newsroom</h3>
						<p class="history-text">Duis iaculis justo nec tellus bibendum rhoncus. Phasellus quis pretium leo, sed porta ligula. Mauris 
							vitae ornare nisi, et dapibus elit. Vestibulum vel urna malesuada, bibendum orci sed, venenatis nunc. Morbi 
							dignissim est tortor, ac aliquam augue blandit at. Pellentesque pulvinar convallis augue, in sodales risus 
							feugiat et. Ut viverra pellentesque tellus eu consectetur. Maecenas eget massa nulla. Fusce convallis et 
							sapien a hendrerit. Etiam viverra maximus dolor, ac tempor sapien.
						</p>
						<div class="about-grids">
							<div class="about-bottom-grids">
								<div class="col-sm-6 about-left">
									<div class="about-left-grids">
										<div class="col-md-2 about-left-img">
											<span class="glyphicon glyphicon-user glyphicon-book" aria-hidden="true"></span>
										</div>
										<div class="col-md-10 about-left-info">
											<a href="#">Tellus eu consectetur</a>
											<p>Suspendisse cursus tempus ullamcorper Praesent molestie urna a metus auctor vulputate molestie urna a metus auctor molestie urna a metus auctor.</p>
										</div>
										<div class="clearfix"> </div>
									</div>
								</div>
								<div class="col-sm-6 about-right">
									<div class="about-left-grids">
										<div class="col-md-2 about-left-img">
											<span class="glyphicon glyphicon-user glyphicon-headphones" aria-hidden="true"></span>
										</div>
										<div class="col-md-10 about-left-info">
											<a href="#">Viverra pellentesque</a>
											<p>Suspendisse cursus tempus ullamcorper Praesent molestie urna a metus auctor vulputate molestie urna a metus auctor molestie urna a metus auctor.</p>
										</div>
										<div class="clearfix"> </div>
									</div>
								</div>
								<div class="clearfix"> </div>
							</div>
							<div class="news-grids">
								<div class="col-md-6 news-left">
									<h3>Statistics</h3>
									<ol>
										<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
										<li>Sed euismod faucibus malesuada dui vitae egestas malesuada ante malesuada Morbi luctus accumsan risus</li>
										<li>Malesuada Sed euismod faucibus dui, vitae egestas ante. Morbi luctus accumsan Sed euismod faucibus dui, vitae egestas ante malesuada Morbi luctus accumsan</li>
										<li>Proin rutrum, turpis at accumsan vestibulum, sem justo aliquam mi, sed bibendum metus risus et odio. Etiam vulputate mauris eget vestibulum lacinia.</li>
										<li>Pellentesque posuere dui a erat pellentesque, eget ultricies tellus rutrum. Mauris et molestie dolor. Phasellus condimentum feugiat</li>
										<li>Integer placerat, eros a ullamcorper venenatis, diam erat vestibulum elit, quis fringilla velit ipsum at dolor.</li>
										<li>Sed euismod faucibus malesuada dui vitae egestas malesuada ante malesuada Morbi luctus accumsan risus</li>
										<li>Malesuada Sed euismod faucibus dui, vitae egestas ante. Morbi luctus accumsan Sed euismod faucibus dui, vitae egestas ante malesuada Morbi luctus accumsan</li>
										<li>Proin rutrum, turpis at accumsan vestibulum, sem justo aliquam mi, sed bibendum metus risus et odio. Etiam vulputate mauris eget vestibulum lacinia.</li>
									</ol>
								</div>
								<div class="col-md-6 news-left news-right">
									<h3>Blogs and Social Media</h3>
									<ol>
										<li><a href="#">Lorem ipsum dolor sit amet</a></li>
										<li><a href="#">Sed euismod faucibus malesuada</a></li>
										<li><a href="#">Malesuada Sed euismod faucibus</a></li>
										<li><a href="#">Proin rutrum, turpis at accumsan</a></li>
										<li><a href="#">Pellentesque posuere dui a erat</a></li>
										<li><a href="#">Integer placerat eros a ullamcorper</a></li>
										<li><a href="#">Sed euismod faucibus malesuada</a></li>
										<li><a href="#">Malesuada Sed euismod faucibus</a></li>
										<li><a href="#">Proin rutrum, turpis at accumsan</a></li>
									</ol>
								</div>
								<div class="clearfix"> </div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- footer -->
			<?php echo Yaf\View\Simple::render(VIEWPATH . '/public/footer.phtml');?> 
			<!-- //footer -->
		</div>
		<div class="clearfix"> </div>
	<div class="drop-menu">
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
		  <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
		  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
		</ul>
	</div> 
  </body>
</html>